### ISSUE TITLE
Option to Dump RabbitMQ Headers and/or Other Properties

### ISSUE THREAD

**Issue by sshaw** [dubek/rabbitmq-dump-queue#1]
In this case I reckon it'd be better to dump the payload to a YAML file with two documents, one with the properties, one with the payload:

``` yaml

---
{
  "priority": 0,
  "timestamp":  1455915599,
  "headers": {
    "foo": "bar"
  }

---
{
   "a": 123,
   "b": 456
}
```

Thoughts?
